Repository Floppa-equipe-16/floppa, pull requests merged in 2023-04, with the labels that each got.

#80 Tests d'intégration
  src/main/java/ulaval/glo2003/api/offer/OfferResource.java
  src/main/java/ulaval/glo2003/api/product/ProductResource.java
  src/main/java/ulaval/glo2003/api/seller/SellerResource.java
  src/test/java/ulaval/glo2003/domain/offer/IOfferRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/offer/OfferTestUtils.java
  src/test/java/ulaval/glo2003/domain/product/IProductRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/product/ProductTestUtils.java
  src/test/java/ulaval/glo2003/domain/seller/ISellerRepositoryITest.java
  src/test/java/ulaval/glo2003/service/integrated/ISellingServiceITest.java
  src/test/java/ulaval/glo2003/service/integrated/InMemorySellingServiceITest.java
  src/test/java/ulaval/glo2003/service/integrated/MongoSellingServiceITest.java
  src/test/java/ulaval/glo2003/service/unit/OfferMapperTest.java
  src/test/java/ulaval/glo2003/service/unit/ProductMapperTest.java
  src/test/java/ulaval/glo2003/service/unit/SellerMapperTest.java
  src/test/java/ulaval/glo2003/service/unit/SellingServiceFactoryTest.java
  src/test/java/ulaval/glo2003/service/unit/SellingServiceTest.java
Labels: test

#79 Sell Product
  src/main/java/ulaval/glo2003/api/offer/SelectedOfferResponse.java
  src/main/java/ulaval/glo2003/api/product/ProductResource.java
  src/main/java/ulaval/glo2003/api/product/ProductResponse.java
  src/main/java/ulaval/glo2003/api/product/ProductSellRequest.java
  src/main/java/ulaval/glo2003/domain/infrastructure/mongo/MongoOffer.java
  src/main/java/ulaval/glo2003/domain/infrastructure/mongo/MongoOfferRepository.java
  src/main/java/ulaval/glo2003/domain/offer/Offer.java
  src/main/java/ulaval/glo2003/domain/offer/OfferFactory.java
  src/main/java/ulaval/glo2003/domain/product/Product.java
  src/main/java/ulaval/glo2003/service/OfferMapper.java
  src/main/java/ulaval/glo2003/service/ProductMapper.java
  src/main/java/ulaval/glo2003/service/SellingService.java
  src/test/java/ulaval/glo2003/api/product/ProductSellRequestTest.java
  src/test/java/ulaval/glo2003/domain/offer/OfferTest.java
  src/test/java/ulaval/glo2003/domain/offer/OfferTestUtils.java
  src/test/java/ulaval/glo2003/domain/product/ProductTestUtils.java
Labels: enhancement

#81 Test e2e
  pom.xml
  src/main/java/ulaval/glo2003/Main.java
  src/main/java/ulaval/glo2003/ResourceConfigProvider.java
  src/main/java/ulaval/glo2003/api/offer/OfferCollectionResponse.java
  src/main/java/ulaval/glo2003/api/offer/OfferRequest.java
  src/main/java/ulaval/glo2003/api/offer/OfferResponse.java
  src/main/java/ulaval/glo2003/api/product/ProductCollectionResponse.java
  src/main/java/ulaval/glo2003/api/product/ProductRequest.java
  src/main/java/ulaval/glo2003/api/product/ProductResponse.java
  src/main/java/ulaval/glo2003/api/seller/SellerRequest.java
  src/main/java/ulaval/glo2003/api/seller/SellerResponse.java
  src/main/java/ulaval/glo2003/domain/exceptions/ErrorDescription.java
  src/main/java/ulaval/glo2003/service/SellingService.java
  src/test/java/ulaval/glo2003/api/offer/OfferCollectionResponseTest.java
  src/test/java/ulaval/glo2003/api/offer/OfferRequestTest.java
  src/test/java/ulaval/glo2003/api/offer/OfferResponseTest.java
  src/test/java/ulaval/glo2003/api/product/ProductCollectionResponseTest.java
  src/test/java/ulaval/glo2003/api/product/ProductRequestTest.java
  src/test/java/ulaval/glo2003/api/product/ProductResponseTest.java
  src/test/java/ulaval/glo2003/api/product/ProductSellRequestTest.java
  src/test/java/ulaval/glo2003/api/seller/SellerRequestTest.java
  src/test/java/ulaval/glo2003/api/seller/SellerResponseTest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/mongo/MongoOfferRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/mongo/MongoProductRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/mongo/MongoSellerRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/offer/IOfferRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/offer/OfferTest.java
  src/test/java/ulaval/glo2003/domain/product/IProductRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/product/ProductTest.java
  src/test/java/ulaval/glo2003/domain/seller/ISellerRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/seller/SellerTest.java
  src/test/java/ulaval/glo2003/e2e/ApiTest.java
  src/test/java/ulaval/glo2003/e2e/HealthResourceTest.java
  src/test/java/ulaval/glo2003/e2e/UsersCreateOffersTest.java
  src/test/java/ulaval/glo2003/e2e/UsersCreateProductsTest.java
  src/test/java/ulaval/glo2003/e2e/UsersCreateSellersTest.java
  src/test/java/ulaval/glo2003/e2e/UsersGetProductByIdTest.java
  src/test/java/ulaval/glo2003/e2e/UsersGetProductsFilterTest.java
  src/test/java/ulaval/glo2003/e2e/UsersGetSellerByIdTest.java
  src/test/java/ulaval/glo2003/e2e/UsersSellProductTest.java
  src/test/java/ulaval/glo2003/service/integrated/ISellingServiceITest.java
  src/test/java/ulaval/glo2003/service/integrated/MongoSellingServiceITest.java
  src/test/java/ulaval/glo2003/service/unit/OfferMapperTest.java
  src/test/java/ulaval/glo2003/service/unit/ProductMapperTest.java
  src/test/java/ulaval/glo2003/service/unit/SellerMapperTest.java
  src/test/java/ulaval/glo2003/service/unit/SellingServiceTest.java
  src/test/java/ulaval/glo2003/utils/MongoTestUtils.java
  src/test/java/ulaval/glo2003/utils/OfferTestUtils.java
  src/test/java/ulaval/glo2003/utils/ProductTestUtils.java
  src/test/java/ulaval/glo2003/utils/SellerTestUtils.java
  src/test/java/ulaval/glo2003/utils/equals/OfferEquals.java
  src/test/java/ulaval/glo2003/utils/equals/OfferEqualsTest.java
  src/test/java/ulaval/glo2003/utils/equals/ProductEquals.java
  src/test/java/ulaval/glo2003/utils/equals/ProductEqualsTest.java
  src/test/java/ulaval/glo2003/utils/equals/SellerEquals.java
  src/test/java/ulaval/glo2003/utils/equals/SellerEqualsTest.java
Labels: test

#82 GitHub planification
  exercices/tp3.md
Labels: documentation

#83 User stories et architecture
  exercices/tp3.md
Labels: documentation

#84 Integration test phase
  .github/workflows/maven-test.yml
  .github/workflows/maven.yml
  pom.xml
  src/test/java/ulaval/glo2003/e2e/CreateOffersITest.java
  src/test/java/ulaval/glo2003/e2e/CreateProductsITest.java
  src/test/java/ulaval/glo2003/e2e/CreateSellersITest.java
  src/test/java/ulaval/glo2003/e2e/GetProductByIdITest.java
  src/test/java/ulaval/glo2003/e2e/GetProductsFilterITest.java
  src/test/java/ulaval/glo2003/e2e/GetSellerByIdITest.java
  src/test/java/ulaval/glo2003/e2e/HealthResourceITest.java
  src/test/java/ulaval/glo2003/e2e/SellProductITest.java
Labels: test

#86 Fix de dernière minute pour le TP3
  src/main/java/ulaval/glo2003/domain/seller/Seller.java
  src/main/java/ulaval/glo2003/service/SellingService.java
  src/test/java/ulaval/glo2003/domain/seller/SellerTest.java
  src/test/java/ulaval/glo2003/e2e/SellProductITest.java
Labels: bug

#87 Fix de vente
  src/main/java/ulaval/glo2003/domain/seller/Seller.java
  src/main/java/ulaval/glo2003/service/SellingService.java
  src/test/java/ulaval/glo2003/domain/seller/SellerTest.java
  src/test/java/ulaval/glo2003/e2e/SellProductITest.java
Labels: bug

#88 last minute fix : missing exception when making offer on sold product
  src/main/java/ulaval/glo2003/service/SellingService.java
  src/test/java/ulaval/glo2003/e2e/CreateOffersITest.java
Labels: bug

#96 Notification couriel
  .github/workflows/maven.yml
  Dockerfile
  docker-compose.yml
  pom.xml
  src/main/java/ulaval/glo2003/EnvironmentVariable.java
  src/main/java/ulaval/glo2003/ResourceConfigProvider.java
  src/main/java/ulaval/glo2003/domain/notification/EmailAuthentication.java
  src/main/java/ulaval/glo2003/domain/notification/EmailHost.java
  src/main/java/ulaval/glo2003/domain/notification/Mail/BlankMail.java
  src/main/java/ulaval/glo2003/domain/notification/Mail/Mail.java
  src/main/java/ulaval/glo2003/domain/notification/Mail/NewOfferMail.java
  src/main/java/ulaval/glo2003/domain/notification/Notification.java
  src/main/java/ulaval/glo2003/domain/notification/SessionException.java
  src/main/java/ulaval/glo2003/service/NotificationService.java
  src/main/java/ulaval/glo2003/service/NotificationServiceFactory.java
  src/main/java/ulaval/glo2003/service/SellingService.java
  src/main/java/ulaval/glo2003/service/SellingServiceFactory.java
  src/main/resources/EmailNotificationConfig.properties
  src/test/java/ulaval/glo2003/domain/notification/NotificationTest.java
  src/test/java/ulaval/glo2003/e2e/ApiTest.java
  src/test/java/ulaval/glo2003/service/integrated/ISellingServiceITest.java
  src/test/java/ulaval/glo2003/service/unit/NotificationServiceFactoryTest.java
  src/test/java/ulaval/glo2003/service/unit/NotificationServiceTest.java
  src/test/java/ulaval/glo2003/service/unit/SellingServiceFactoryTest.java
  src/test/java/ulaval/glo2003/service/unit/SellingServiceTest.java
  src/test/java/ulaval/glo2003/utils/EnvironmentVarMock.java
  src/test/java/ulaval/glo2003/utils/SellerTestUtils.java
Labels: enhancement

#97 Seller ranking
  src/main/java/ulaval/glo2003/api/product/ProductsStatsResponse.java
  src/main/java/ulaval/glo2003/api/seller/SellerCollectionResponse.java
  src/main/java/ulaval/glo2003/api/seller/SellerResource.java
  src/main/java/ulaval/glo2003/api/seller/SellerResponse.java
  src/main/java/ulaval/glo2003/domain/infrastructure/inMemory/InMemorySellerRepository.java
  src/main/java/ulaval/glo2003/domain/infrastructure/mongo/MongoSeller.java
  src/main/java/ulaval/glo2003/domain/infrastructure/mongo/MongoSellerRepository.java
  src/main/java/ulaval/glo2003/domain/seller/ISellerRepository.java
  src/main/java/ulaval/glo2003/domain/seller/Seller.java
  src/main/java/ulaval/glo2003/domain/seller/SellerFactory.java
  src/main/java/ulaval/glo2003/service/SellerMapper.java
  src/main/java/ulaval/glo2003/service/SellingService.java
  src/test/java/ulaval/glo2003/domain/seller/ISellerRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/seller/SellerTest.java
  src/test/java/ulaval/glo2003/e2e/GetRankedSellersITest.java
  src/test/java/ulaval/glo2003/service/integrated/ISellingServiceITest.java
  src/test/java/ulaval/glo2003/service/unit/SellerMapperTest.java
  src/test/java/ulaval/glo2003/service/unit/SellingServiceTest.java
  src/test/java/ulaval/glo2003/utils/SellerTestUtils.java
  src/test/java/ulaval/glo2003/utils/equals/SellerEquals.java
Labels: enhancement

#98 Adding code analysis tools
  .github/workflows/maven-test.yml
  .github/workflows/maven.yml
  exercices/tp4.md
  pom.xml
Labels: enhancement

#101 Moved infrastructure file out of domain layer.
  src/main/java/ulaval/glo2003/infrastructure/inMemory/InMemoryOfferRepository.java
  src/main/java/ulaval/glo2003/infrastructure/inMemory/InMemoryProductRepository.java
  src/main/java/ulaval/glo2003/infrastructure/inMemory/InMemorySellerRepository.java
  src/main/java/ulaval/glo2003/infrastructure/mongo/MongoOffer.java
  src/main/java/ulaval/glo2003/infrastructure/mongo/MongoOfferRepository.java
  src/main/java/ulaval/glo2003/infrastructure/mongo/MongoProduct.java
  src/main/java/ulaval/glo2003/infrastructure/mongo/MongoProductRepository.java
  src/main/java/ulaval/glo2003/infrastructure/mongo/MongoSeller.java
  src/main/java/ulaval/glo2003/infrastructure/mongo/MongoSellerRepository.java
  src/main/java/ulaval/glo2003/service/SellingServiceFactory.java
  src/test/java/ulaval/glo2003/e2e/ApiTest.java
  src/test/java/ulaval/glo2003/infrastructure/inMemory/InMemoryOfferRepositoryITest.java
  src/test/java/ulaval/glo2003/infrastructure/inMemory/InMemoryProductRepositoryITest.java
  src/test/java/ulaval/glo2003/infrastructure/inMemory/InMemorySellerRepositoryITest.java
  src/test/java/ulaval/glo2003/infrastructure/mongo/MongoOfferRepositoryITest.java
  src/test/java/ulaval/glo2003/infrastructure/mongo/MongoProductRepositoryITest.java
  src/test/java/ulaval/glo2003/infrastructure/mongo/MongoSellerRepositoryITest.java
  src/test/java/ulaval/glo2003/service/integrated/InMemorySellingServiceITest.java
  src/test/java/ulaval/glo2003/service/integrated/MongoSellingServiceITest.java
Labels: refactoring

#100 Planification du travail sur Github
  exercices/tp4.md
Labels: documentation

#102 Open sourcing
  exercices/tp4.md
Labels: documentation

#99 Publication
  .github/workflows/maven.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.txt
  README.md
  exercices/tp4.md
Labels: documentation
