Repository Floppa-equipe-16/floppa, pull requests merged in 2023-03, with the labels that each got.

#58 Refactor : Make OfferValidator a package only class, and removed unne…
  src/main/java/ulaval/glo2003/domain/offer/OfferValidator.java
Labels: refactoring

#73 Retrospective
  exercices/tp3.md
Labels: documentation

#75 Setup database
  .github/workflows/maven.yml
  pom.xml
  src/main/java/ulaval/glo2003/Main.java
  src/main/java/ulaval/glo2003/api/HealthResource.java
  src/main/java/ulaval/glo2003/api/HealthResponse.java
  src/main/java/ulaval/glo2003/api/LostResource.java
  src/main/java/ulaval/glo2003/domain/infrastructure/inMemory/InMemoryOfferRepository.java
  src/main/java/ulaval/glo2003/domain/infrastructure/inMemory/InMemoryProductRepository.java
  src/main/java/ulaval/glo2003/domain/infrastructure/inMemory/InMemorySellerRepository.java
  src/main/java/ulaval/glo2003/domain/infrastructure/mongo/MongoOffer.java
  src/main/java/ulaval/glo2003/domain/infrastructure/mongo/MongoOfferRepository.java
  src/main/java/ulaval/glo2003/domain/infrastructure/mongo/MongoProduct.java
  src/main/java/ulaval/glo2003/domain/infrastructure/mongo/MongoProductRepository.java
  src/main/java/ulaval/glo2003/domain/infrastructure/mongo/MongoSeller.java
  src/main/java/ulaval/glo2003/domain/infrastructure/mongo/MongoSellerRepository.java
  src/main/java/ulaval/glo2003/domain/offer/IOfferRepository.java
  src/main/java/ulaval/glo2003/domain/product/IProductRepository.java
  src/main/java/ulaval/glo2003/domain/seller/ISellerRepository.java
  src/main/java/ulaval/glo2003/service/SellingServiceFactory.java
  src/test/java/ulaval/glo2003/domain/infrastructure/inMemory/InMemoryOfferRepositoryTest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/inMemory/InMemoryProductRepositoryTest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/inMemory/InMemorySellerRepositoryTest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/mongo/MongoOfferRepositoryTest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/mongo/MongoProductRepositoryTest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/mongo/MongoSellerRepositoryTest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/mongo/MongoTestUtils.java
  src/test/java/ulaval/glo2003/domain/offer/IOfferRepositoryTest.java
  src/test/java/ulaval/glo2003/domain/product/IProductRepositoryTest.java
  src/test/java/ulaval/glo2003/domain/seller/ISellerRepositoryTest.java
  src/test/java/ulaval/glo2003/service/SellingServiceFactoryTest.java
Labels: enhancement

#77 Add sale status to database
  src/main/java/ulaval/glo2003/domain/infrastructure/mongo/MongoProduct.java
  src/main/java/ulaval/glo2003/domain/infrastructure/mongo/MongoProductRepository.java
  src/main/java/ulaval/glo2003/domain/product/Product.java
  src/main/java/ulaval/glo2003/domain/product/ProductFactory.java
  src/test/java/ulaval/glo2003/api/product/ProductEquals.java
  src/test/java/ulaval/glo2003/domain/product/IProductRepositoryTest.java
  src/test/java/ulaval/glo2003/domain/product/ProductTest.java
  src/test/java/ulaval/glo2003/domain/product/ProductTestUtils.java
Labels: enhancement

#78 Déploiment
  .github/workflows/docker-build.yml
  .github/workflows/maven-test.yml
  .github/workflows/packaging-production.yml
  .github/workflows/packaging-staging.yml
  Dockerfile
  docker-compose.yml
  pom.xml
  src/main/java/ulaval/glo2003/Main.java
  src/main/java/ulaval/glo2003/api/HealthResource.java
  src/test/java/ulaval/glo2003/domain/infrastructure/inMemory/InMemoryOfferRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/inMemory/InMemoryProductRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/inMemory/InMemorySellerRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/mongo/MongoOfferRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/mongo/MongoProductRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/infrastructure/mongo/MongoSellerRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/offer/IOfferRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/product/IProductRepositoryITest.java
  src/test/java/ulaval/glo2003/domain/seller/ISellerRepositoryITest.java
Labels: enhancement
